\hypertarget{structPyUnicodeErrorObject}{}\section{Py\+Unicode\+Error\+Object Struct Reference}
\label{structPyUnicodeErrorObject}\index{Py\+Unicode\+Error\+Object@{Py\+Unicode\+Error\+Object}}
\subsection*{Public Attributes}
\begin{DoxyCompactItemize}
\item 
Py\+Exception\+\_\+\+H\+E\+AD \hyperlink{struct__object}{Py\+Object} $\ast$ {\bfseries encoding}\hypertarget{structPyUnicodeErrorObject_a62191f79a51fdb37ce1351928bf44c19}{}\label{structPyUnicodeErrorObject_a62191f79a51fdb37ce1351928bf44c19}

\item 
\hyperlink{struct__object}{Py\+Object} $\ast$ {\bfseries object}\hypertarget{structPyUnicodeErrorObject_a7c7f8d33cacfb75d3383b6f1ad354e16}{}\label{structPyUnicodeErrorObject_a7c7f8d33cacfb75d3383b6f1ad354e16}

\item 
Py\+\_\+ssize\+\_\+t {\bfseries start}\hypertarget{structPyUnicodeErrorObject_a21a6e41da10c007992474a3577bf8ede}{}\label{structPyUnicodeErrorObject_a21a6e41da10c007992474a3577bf8ede}

\item 
Py\+\_\+ssize\+\_\+t {\bfseries end}\hypertarget{structPyUnicodeErrorObject_aa044eb7ce2644cb89b9fe9d431b9bce6}{}\label{structPyUnicodeErrorObject_aa044eb7ce2644cb89b9fe9d431b9bce6}

\item 
\hyperlink{struct__object}{Py\+Object} $\ast$ {\bfseries reason}\hypertarget{structPyUnicodeErrorObject_aebf54b5060cf56c47e5661a22bfcc4c3}{}\label{structPyUnicodeErrorObject_aebf54b5060cf56c47e5661a22bfcc4c3}

\end{DoxyCompactItemize}


\subsection{Detailed Description}


Definition at line 37 of file pyerrors.\+h.



The documentation for this struct was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/usr/include/python3.\+5m/pyerrors.\+h\end{DoxyCompactItemize}
